c_compiler:    # [osx]
  - clang      # [osx]
cxx_compiler:  # [osx]
  - clangxx    # [osx]
c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]