c_compiler:    # [osx]
  - clang      # [osx]
cxx_compiler:  # [osx]
  - clangxx    # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]