{% set name = "openmeeg" %}
{% set version = "2.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  url: https://github.com/larsoner/openmeeg/archive/70e09f0b38216f29783474470b31ee0d49d6ee80.tar.gz
  sha256: d25deea1fc11b72a6bbaf4b215b6d0ac2c831ac919b0a148cf52c29e1e2066f9

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.19
    - make
    - ninja  # [not win]
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pthread-stubs  # [win]
    - swig

  host:
    - python
    - numpy
    - hdf5  # [win]
    - hdf5-static  # [not win]
    - libgfortran  # [not win]
    - openblas
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgfortran  # [not win]
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  commands:
    - python -c "import openmeeg; assert openmeeg.sqr(4) == 16"

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
    - larsoner
