{% set name = "openmeeg" %}
{% set version = "2.5.3" %}
{% set sha256 = "f065854c0f2410611ace2d3780e57e986bb8f5314b1b1d7e30e6dc06f07657b5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.19
    - make
    - ninja  # [not win]
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # just for OpenBLAS to link properly
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pthread-stubs  # [win]
    - swig

  host:
    - python
    - numpy
    - hdf5
    - openblas
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgfortran  # [not win]
    - libgfortran5  # [not win]
    - ucrt  # [win]
    - libopenblas
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  requires:
    - pytest
  source_files:
    - data
  commands:
    - python run_test.py
    - om_minverser --help

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
    A C++ package for solving the forward problems of electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - agramfort
    - larsoner
