{% set version = "2.4.1" %}

package:
  name: openmeeg
  version: {{ version }}

source:
  # TODO: PR and merge https://github.com/larsoner/openmeeg/commits/conda-forge
  url: https://github.com/larsoner/openmeeg/archive/725be4414bcf88900346dd863dda3a438072d487.tar.gz
  sha256: 8d88f61f443533ab5055a1dca29adafa3c6758d87a15b2989ad39b53d48893f8
  # patches:
  #   - overwrite_opnmeegpy_installation_path_win.patch  # [win]

build:
  number: 201

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.8
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python
    - numpy
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - openblas
    - swig
    - hdf5
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libblas * *openblas
    - openblas
    - hdf5
    - zlib
    - libmatio

test:
  imports:
    - openmeeg

about:
  home: https://openmeeg.github.io/
  license: CeCILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
    - larsoner
