{% set version = "2.4.1" %}

package:
  name: openmeeg
  version: {{ version }}

source:
  # TODO: PR and merge https://github.com/larsoner/openmeeg/commits/conda-forge
  url: https://github.com/larsoner/openmeeg/archive/9fd7d654883749e8c6b2cc6225ace8428ec47438.tar.gz
  sha256: 0764b1650e0a5db44667f59087ea2bb70bb2ef3374bfa48258a41c70f19e4465
  # patches:
  #   - overwrite_opnmeegpy_installation_path_win.patch  # [win]

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 201
  # For now, skip Windows entirely. We can reenable it after we fix things
  # on OpenMEEG's CIs
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - cmake >=3.8
    - make
    - ninja
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python
    - numpy
    - pthread-stubs  # [win]
    - openblas
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - swig
    - hdf5
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libblas * *openblas
    - openblas
    - hdf5
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  commands:
    - python -c "import openmeeg; assert openmeeg.sqr(4) == 16"

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
    - larsoner
