{% set version = "2.4.1" %}
{% set build_number = 1 %}

{% set variant = "openblas" %}
{% set build_number = build_number + 200 %}

package:
  name: openmeeg
  version: {{ version }}

source:
  url: https://github.com/openmeeg/openmeeg/archive/865ce622e8a6afd7a4ce8884a9d3e6f8d4f92ac6.tar.gz
  sha256: fa83f8f6777d26afc3306a7f4c8226376d2682c0e9f83de26a55cb7b6f8f4f6e
  patches:
    - overwrite_opnmeegpy_installation_path_win.patch  # [win]

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake >=3.8
    - make
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - blas 1.1 {{ variant }}
    - openblas
    - swig
    - hdf5
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blas 1.1 {{ variant }}
    - openblas
    - hdf5
    - zlib
    - libmatio
    - openmp  # [osx]

test:
  imports:
    - openmeeg

about:
  home: http://openmeeg.github.io/
  license: CeCILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
    - larsoner
