{% set version = "2.4.1" %}
{% set build_number = 1000 %}

{% set variant = "openblas" %}
{% set build_number = build_number + 200 %}

package:
  name: openmeeg
  version: {{ version }}

source:
  url: https://github.com/openmeeg/openmeeg/archive/{{ version }}.tar.gz
  sha256: bcc6782b7aa3a5d36ec1b4c18544083cb93541d63dd098b6686098774974f571
  patches:
    - overwrite_opnmeegpy_installation_path_win.patch  # [win]

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake >=3.8
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy  # [not win]
    - numpy 1.14  # [win]
    - blas 1.1 {{ variant }}
    - openblas
    - swig
    - hdf5 1.8.18|1.8.18.*
    - zlib
    - libmatio
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blas 1.1 {{ variant }}
    - openblas
    - hdf5 1.8.18|1.8.18.*
    - zlib
    - libmatio
    - openmp 4.0.*  # [osx]

test:
  imports:
    - openmeeg

about:
  home: http://openmeeg.github.io/
  license: CeCILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
