{% set name = "openmeeg" %}
{% set version = "2.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: de47a5207f6c58ac91d4fb025c11adc7b6741524c0968a67857d40d814752594

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.19
    - make
    - ninja  # [not win]
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # just for OpenBLAS to link properly
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pthread-stubs  # [win]
    - swig

  host:
    - python
    - numpy
    - hdf5
    - openblas
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgfortran  # [not win]
    - libgfortran5  # [not win]
    - ucrt  # [win]
    - libopenblas
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  requires:
    - pytest
    - bash
  source_files:
    - build_tools/cibw_test_command.sh
    - data
  commands:
    - om_minverser --help
    - bash "./build_tools/cibw_test_command.sh"

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
    A C++ package for solving the forward problems of electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - agramfort
    - larsoner
