{% set name = "openmeeg" %}
{% set version = "2.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # TODO: PR and merge https://github.com/larsoner/openmeeg/commits/conda-forge
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 12105b1f29b41e76ca48280ae422ae8fc8f540c838f42186f46bd7d143a301d4
  patches:
    - fix_soabi.patch

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 0
  script_env:
   - OS=osx  # [osx]
   - OS=linux  # [linux]
   - OS=win  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.8
    - make
    - ninja
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pthread-stubs  # [win]
    - swig

  host:
    - python
    - numpy
    - hdf5  # [win]
    - hdf5-static  # [not win]
    - openblas
    - libgfortran
    - zlib
    - libmatio
    - setuptools
    - pip
    - wheel
    - delocate  # [osx]
    - auditwheel  # [linux]
    - delvewheel  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgfortran
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  commands:
    - python -c "import openmeeg; assert openmeeg.sqr(4) == 16"

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - massich
    - agramfort
    - larsoner
