{% set name = "openmeeg" %}
{% set version = "2.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/822fc8a92b916c68c0ab0c5d561b1d3af44b52f3.tar.gz
  sha256: 971aac54fc7bfb5b2ee94cb4df09a4c2aff461fb0097f89cdd62f6aeafd19270

# https://conda-forge.org/docs/maintainer/knowledge_base.html
build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.19
    - make
    - ninja  # [not win]
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pthread-stubs  # [win]
    - swig

  host:
    - python
    - numpy
    - hdf5  # [win]
    - hdf5-static  # [not win]
    - libgfortran  # [not win]
    - libgfortran5  # [not win]
    - openblas
    - zlib
    - libmatio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgfortran  # [not win]
    - ucrt  # [win]
    - libopenblas  # [win]
    - zlib
    - libmatio

test:
  imports:
    - openmeeg
  requires:
    - pytest
  source_files:
    - build_tools/cibuildwheel_test_command.sh
    - data

about:
  home: https://openmeeg.github.io/
  license: CECILL-B
  license_file: LICENSE.txt
  summary: >
           A C++ package for solving the forward problems of
           electroencephalography (EEG) and magnetoencephalography (MEG).

extra:
  recipe-maintainers:
    - agramfort
    - larsoner
