travis:
  secure:
    BINSTAR_TOKEN: i0xJT7AcMBkewdzOgv4rTvOwj+RfSjNimC6p34kowoQm6QHquMnVzRX4zcf9RSxIdVDB4VdTuAbYKuYE/sIXd+8MRyPUXA9lKBx95EgS4sKcptQVYUBFUzH5GI36L1fI+C5YHx/lorTW1UwohmhlNPVdEXm05U5I3ukVn15tISFr435pPkTpkbx9uEi3Cll1vgJfaHjdoqz8WGoCoeH8avJadJmI6BmejQ2qCUaZUF+WFFjoOxyn3N69NPM4hbCv+6uIyMRU8r9uBT5A23BGb09j6Ewap4RmErT0RIhRC8xCng9+hioPkAqkTcz212lU4So340eOYOocd8rGJuk8f+ZgPiqcmqD1oNIC2/ZaJXpiXff1l4smZ+GCf8gToteSh9+CbEsoqoIiiG8D/klOTSA6aUv41SgT3YRvMA4u+1D343/Cyt4ZmypuED9ESkOgqH4xe4hRxRmKA7V9MIvg/wgQipHOekV9ofitYXBGJj7JfAtcEyzKXgMQWGLyxnAWkPK0dBYdhbFufYjRHQf+qfDU4ulgQeh1Ws7gIRVmCmZ8l1RacsOqipJYc3RET3mdL2qN8ifjitXFdzM8IlKfD6PT/GaVCAcyT3jfvNvjcyDcHRxPch/Tm6nJd58p+hvXz3JsHosr03A3Sc7RjCFEMUJg6YWX25Mr8zB+F/mPUJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
