bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  # Could NOT find Python3 (missing: Python3_INCLUDE_DIRS ...
  # so skip for now. Also, can't natively test.
  linux_ppc64le: None
  win: azure
test: native_and_emulated
